// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

import { c, b4a, assert } from 'hyperdispatch/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null

    this._missing = 4
  }

  add (name, handler) {
    switch (name) {
      case '@basic-photo-backup/add-writer':
        this._handler0 = handler
        break
      case '@basic-photo-backup/add-invite':
        this._handler1 = handler
        break
      case '@basic-photo-backup/add-video':
        this._handler2 = handler
        break
      case '@basic-photo-backup/add-message':
        this._handler3 = handler
        break
      default:
        throw new Error('Cannot register a handler for a nonexistent route: ' + name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@basic-photo-backup/add-writer"')
    assert(this._handler1 !== null, 'Missing handler for "@basic-photo-backup/add-invite"')
    assert(this._handler2 !== null, 'Missing handler for "@basic-photo-backup/add-video"')
    assert(this._handler3 !== null, 'Missing handler for "@basic-photo-backup/add-message"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      default:
        throw new Error('Handler not found for ID:' + op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@basic-photo-backup/add-writer',
  id: 0,
  enc: getEncoding('@basic-photo-backup/writer')
}

const route1 = {
  name: '@basic-photo-backup/add-invite',
  id: 1,
  enc: getEncoding('@basic-photo-backup/invite')
}

const route2 = {
  name: '@basic-photo-backup/add-video',
  id: 2,
  enc: getEncoding('@basic-photo-backup/video')
}

const route3 = {
  name: '@basic-photo-backup/add-message',
  id: 3,
  enc: getEncoding('@basic-photo-backup/message')
}

function getRouteByName (name) {
  switch (name) {
    case '@basic-photo-backup/add-writer':
      return route0
    case '@basic-photo-backup/add-invite':
      return route1
    case '@basic-photo-backup/add-video':
      return route2
    case '@basic-photo-backup/add-message':
      return route3
    default:
      throw new Error('Handler not found for name: ' + name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    default:
      throw new Error('Handler not found for ID: ' + id)
  }
}

export {
  version,
  encode,
  decode,
  Router
}
