// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

import { c, RPC, RPCStream, RPCRequestStream } from 'hrpc/runtime'
import { getEncoding } from './messages.js'

const methods = new Map([
  ['@basic-live-cam/videos', 0],
  [0, '@basic-live-cam/videos'],
  ['@basic-live-cam/add-video', 1],
  [1, '@basic-live-cam/add-video'],
  ['@basic-live-cam/messages', 2],
  [2, '@basic-live-cam/messages'],
  ['@basic-live-cam/add-message', 3],
  [3, '@basic-live-cam/add-message']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@basic-live-cam/videos', getEncoding('@basic-live-cam/videos')],
      ['@basic-live-cam/add-video', c.string],
      ['@basic-live-cam/messages', getEncoding('@basic-live-cam/messages')],
      ['@basic-live-cam/add-message', getEncoding('@basic-live-cam/add-message')]
    ])
    this._responseEncodings = new Map([
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  videos(args) {
    return this._callSync('@basic-live-cam/videos', args)
  }

  addVideo(args) {
    return this._callSync('@basic-live-cam/add-video', args)
  }

  messages(args) {
    return this._callSync('@basic-live-cam/messages', args)
  }

  addMessage(args) {
    return this._callSync('@basic-live-cam/add-message', args)
  }

  onVideos(responseFn) {
    this._handlers['@basic-live-cam/videos'] = responseFn
  }

  onAddVideo(responseFn) {
    this._handlers['@basic-live-cam/add-video'] = responseFn
  }

  onMessages(responseFn) {
    this._handlers['@basic-live-cam/messages'] = responseFn
  }

  onAddMessage(responseFn) {
    this._handlers['@basic-live-cam/add-message'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@basic-live-cam/videos',
      '@basic-live-cam/add-video',
      '@basic-live-cam/messages',
      '@basic-live-cam/add-message'
    ].includes(command)
  }
}

export default HRPC
